# Generated by Django 3.0.8 on 2020-07-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20200725_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientlogo',
            field=models.ImageField(blank=True, null=True, upload_to='clientimg/', verbose_name='Client Logo'),
        ),
    ]
