# Generated by Django 3.0.8 on 2020-07-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20200725_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Desciption',
            field=models.TextField(blank=True, null=True, verbose_name='Desciption'),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientactive',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
