# Generated by Django 3.0.8 on 2020-07-24 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', 'posttitle']},
        ),
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(null=True, verbose_name='Post Content'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='mainimg',
            field=models.ImageField(blank=True, null=True, upload_to='pstimg/', verbose_name='Header Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='postimg',
            field=models.ImageField(blank=True, null=True, upload_to='pstimg/', verbose_name='Post Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='posttitle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
