# Generated by Django 3.0.8 on 2020-07-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servname', models.CharField(default='Service_name', max_length=50, verbose_name='Service Name')),
                ('servimg', models.ImageField(blank=True, null=True, upload_to='servimg/', verbose_name='Service Image')),
                ('servdesc', models.TextField(blank=True, null=True, verbose_name='Service Decsription')),
                ('mainserv', models.ForeignKey(blank=True, limit_choices_to={'mainserv__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Service', verbose_name='Main Service')),
            ],
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
