# Generated by Django 3.0.8 on 2020-07-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200724_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='servactive',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
