# Generated by Django 3.0.8 on 2020-07-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['revname']},
        ),
        migrations.AddField(
            model_name='review',
            name='revactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='revcontent',
            field=models.TextField(null=True, verbose_name='Review Content'),
        ),
        migrations.AddField(
            model_name='review',
            name='revimg',
            field=models.ImageField(blank=True, null=True, upload_to='pstimg/', verbose_name='Client Image'),
        ),
        migrations.AddField(
            model_name='review',
            name='revlink',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='review',
            name='revname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Client Name'),
        ),
    ]
