# Generated by Django 3.0.8 on 2020-07-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20200725_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='active',
        ),
        migrations.AddField(
            model_name='review',
            name='revactive',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='review',
            name='revcontent',
            field=models.TextField(blank=True, null=True, verbose_name='Review Content'),
        ),
        migrations.AlterField(
            model_name='review',
            name='revlink',
            field=models.URLField(blank=True, null=True, verbose_name='Review Link'),
        ),
    ]
